### ISSUE TITLE
Hyperapp >=2.0.5 Compatibility

### ISSUE THREAD

**Issue by kevinfiol** [fuzetsu/microh#5]
Hey there, great library! This is exactly what I was looking for in my next project. Coming from Mithril, I got spoiled by its hyperscript helper. Also, clever that the m in `m()` stands for `microh`, but looks like Mithril. :+1: 

As you may know, newer versions of Hyperapp post-v2.0.4 introduce the `text()` function for text nodes, and is now incompatible with other implementations of hyperscript. As such, writing `h('p', {}, 'foo')` is no longer valid. You must now write `h('p', {}, text('foo'))`. This also applies to primitive number values, so you must also write `h('p', {}, text(5))` if that's your intention.

The author of Hyperapp writes [here](https://github.com/jorgebucaran/hyperapp/issues/980#issuecomment-683372749) about using newer versions of Hyperapp with JSX. Although microh has nothing to do with JSX, this comment was helpful in writing a function to pass to microh. [Here's an example of this working in Flems](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ADAOjQRgDQgGd4EBjAF3imRAwAsyxYR8AzCBA5AbVADsBDMIiQ16jZiBIB7XhVnUAPARIAnCAAcyAAjIBPdfAC8AHXBSoAVwSmAfMd5atEMOqkrtwLbVw74ADzIffnV1LQBfLRYVKTAtU3oydQIkAHoUi151AGsAcwxpMBTafXgVYPUAAQAmLAwADlN7R2dXdy1IVSlaSOjYgHIEpNT0zNz8mJSO6NoKzGwsAH4wcyt4PoBuJriHLWleAm1Yw3aITtoACnOyfhyfdWiknwxnklp2KBV4XgBKLUMbLTALaOT5kCwqBx6AxSFg6G5-QzHUwsDLkCAyRo7RyOBZwnLne5SR67N6wD5fb7A7FILznKnY7HXW70hlaQlJLQAH05gLCuBZDK4AF0BazxrwSPwyOdnvlSeSfqKGRgwMFLvxeLpfv8layofAYVoNboEUjCGQ1LwcqYuTz9Ybjaa4iBeBYwAAjUo23EUALnY2-GnG3WOSlY1lhxxhb6bXhbPYHLQAYXlfy0BIeBB8r3enx+fzs4bA5z6UAgADc+vzw45iwMAMxVrR9FPvZMxVy8L5kPrfaus9ol9RNvqu2JkZzwAhaKo0vpaADUbMzGDHWgAVDO+yy62XK9n5XnI9iw-GZImAJIStMHKXwAvpzyy28UHxjmkv+Crt2LrTYcIxme+zaAAIvAJA3tcFAPucT7PJ+b5uh+UFfmuAC0f4AbGWzlLBVIQLwEBkDSnjvloaDhP22LlhA8AAO40rBWhrtGD47iWe5VqKda0NgI7FAYZQhDOtR1L2VEDjxVRNp4By6AgJG7FIsBuHOnxQPOER8sxbrbjW2J1u6FhkGQMgyVoMgkLApxZDSV4QdpfQEao8BCLI4ncSWRkmWZPieJZ1kkLZWhgQ5PiluBnxuT2ekDrW5ytmSfk6bEjk5mSeYWbCiUaceDKxdivDmPANJQFIJBut2GDuuYuhUdG9gKCkyhqJoNgSEQpATue1D1gAbEgVR9Wh-VIAALAArCAfJ8IIwg0AAVpw+B7HIZDUNNuCzUI1D5AQy2SDIa0bWEQphEAA).

Less of an issue, but still worth considering: Vnodes generated by Hyperapp's new `text()` function are invalid with microh *if* the value passed to `text()` is falsey. This is because writing `text(0)` or `text('')` for example, will generate these respectively:

```js
{ type: 0, props: {}, children: [], node: undefined, key: null, tag: 3 }
{ type: '', props: {}, children: [], node: undefined, key: null, tag: 3 }
```

microh will use the `type` property as the `tagKey` here on [this line](https://github.com/fuzetsu/microh/blob/aef97bba123062bb3f24a651a0b645abdc041cfb/microh.js#L23), and so the children will be shifted. [Here's the incompatibility in action](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ADAOjQRgDQgGd4EBjAF3imRAwAsyxYR8AzCBA5AbVADsBDMIiQ16jZiBIB7XhVnUAPARIAnCAAcyAAjIBPdfAC8AHXBSoAVwSmAfMd5atEMOqkrtwLbVw74ADzIffnV1LQBfLRYVKTAtU3oydQIkAHoUi151AGsAcwxpMBTafXgVYPUAAQAmLAwADlN7R2dXdy1IVSlaSOjYgHIEpNT0zNz8mJSO6NoKzGwsAH4wcyt4PoBuJriHLWleAm1Yw3aITtoACloASk2drfLz4C3m3ggyJC1PXgswD7Rw3DPLQANwg8AA7h9HlpvrEwlctIYbNtHKj2uc+lAIMC+j4uEC0WkdLR4EQtOC3FkkATUWAMepcb4AudsFcroCdmjHHS+gyfBRmQNiLApH02RyuaiaY4iWQSWSAEYqeD8KnSrREnl8plkc5ocXqzX0xkC3V9MVXGkAXXZQN45ngHygUhIP3gsgwCvMugl4UtvAUKWUak0NgkRFIZAgMk4IgALEgqlUQGFcHxBMIaAArTj4PZyMjUFNpkACITUfIEXOSGQFothK1hIA)

As Hyperapp now strays from normal hyperscript implementations, it might be silly for microh to chase compatibility with it until its API is stable. These breaking changes in Hyperapp occurred between `2.0.4` and `2.0.5`, so it's hard to predict if you instinctively follow semver. It might, however, be worth adding a disclaimer in the README that Hyperapp versions past `2.0.4` require additional code to work with microh.

**Comment by fuzetsu** [comment]
Sorry for late reply on this.. 

I'm really glad you like `microh` 😄 

Thanks for the heads up on this and the detailed explanation/links. I haven't been keeping up with hyperapp recently so I was not aware of these changes!

I agree with your recommendation to add a note in the readme and not try to chase compatibility. https://github.com/fuzetsu/microh/commit/785ec3127bffb2634ec99af71e127a48888e3f69

I will say that microh arguably still works fine with hyperapp out of the box. The user would have to wrap with `text` manually on their side. Which could be a fair expectation.

```js
import { h, text } from 'hyperapp'
import microh from 'microh'

const m = microh(h)

const Cmp = (props, children) => {
  return m(
    'main', 
    Header('Hello world'),
    m('p', text('Lorem ipsum'))
  )
}

const Header = title => m('h1', text(title))
```

Although I have to say, `text` is a bit strange, kind of makes it hard to know when you need to call it or not like in the `Header` example, do I call it in the component, or in the parent? 🤔 

Using the custom snippet that auto wraps in `text` and handles component functions though is definitely a nicer experience and would make it easier to reuse components from mithril or wherever.
